<div class="modal fade" id="modalTerms" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title m-auto text-center modal-header" id="header-tittle">Términos y condiciones</h5>
                <button type="button" class="close m-0 p-0 modal-close-button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="margin-right: 3%;">
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Dando cumplimiento a lo dispuesto en la Ley 1581 de 2012, &quot;Por el cual se dictan disposiciones&nbsp;</span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">generales para la protecci&oacute;n de datos personales&quot; y de conformidad con lo se&ntilde;alado en el Decreto&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1377 de 2013, con la aceptaci&oacute;n de este texto manifiesto que he sido informado por MEZAMU de lo siguiente:</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1. MEZAMU actuar&aacute; como Responsable del Tratamiento de datos personales de los cuales soy&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">titular y que, conjunta o separadamente podr&aacute; recolectar, usar y tratar mis datos personales&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">conforme la Pol&iacute;tica de Tratamiento de Datos Personales MEZAMU disponible en la p&aacute;gina&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">web de la entidad.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. Que me ha sido informada la (s) finalidad (es) de la recolecci&oacute;n de los datos personales.&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">3. Es de car&aacute;cter facultativo o voluntario responder preguntas que versen sobre Datos Sensibles&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">o sobre menores de edad.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4. Mis derechos como titular de los datos son los previstos en la Constituci&oacute;n y la ley,&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">especialmente el derecho a conocer, actualizar, rectificar y suprimir mi informaci&oacute;n personal, as&iacute;&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">como el derecho a revocar el consentimiento otorgado para el tratamiento de datos personales.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5. Los derechos pueden ser ejercidos a trav&eacute;s de los canales dispuestos por MEZAMU y&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">observando la Pol&iacute;tica de Tratamiento de Datos Personales de MEZAMU.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6. Mediante la p&aacute;gina web de la entidad (www.mezamu.com), podr&eacute; radicar cualquier tipo de&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">requerimiento relacionado con el tratamiento de mis datos personales.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">7. MEZAMU garantizar&aacute; la confidencialidad, libertad, seguridad, veracidad, transparencia, acceso&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">y circulaci&oacute;n restringida de mis datos y se reservar&aacute; el derecho de modificar su Pol&iacute;tica de&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tratamiento de Datos Personales en cualquier momento. Cualquier cambio ser&aacute; informado y&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">publicado oportunamente en la p&aacute;gina web.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">8. Teniendo en cuenta lo anterior, autorizo de manera voluntaria, previa, expl&iacute;cita, informada e&nbsp;</span></span><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">inequ&iacute;voca a MEZAMU para tratar mis datos personales de acuerdo con su Pol&iacute;tica de Tratamiento de Datos Personales para los fines relacionados con su objeto y en especial para fines legales, contractuales, misionales descritos en la Pol&iacute;tica de Tratamiento de Datos Personales de MEZAMU.</span></span></p>
                <p dir="ltr" style="line-height: 1.295; margin-top: 0pt; margin-bottom: 8pt; text-align: justify; margin-left: 20px;"><span style="font-size: 11px;"><span style="font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9. La informaci&oacute;n obtenida para el Tratamiento de mis datos personales la he suministrado de&nbsp;</span></span><span style="font-size: 11px; font-family: Calibri, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">forma voluntaria y es ver&iacute;dica.&nbsp;</span></p>
            </div>    
        </div>
    </div>
</div>


